name: Build Gateway Modules

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          tools-deps: '1.10.1.483'
          lein: '2.9.1'

      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm

      - name: Cache Git dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gitlibs
          key: gitlibs

      - name: Build
        run: lein modules install

      - name: Test
        run: lein modules test

      - name: Test JS
        run: lein with-profiles +cljs modules shadow-cljs compile test
